### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by kleinpa** [dspzl/dspzl.org#12]
To enable HTTPS on dspzl.org like we need to update our DNS records.

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

Currently, the records look like 

```sh
$ dig dspzl.org
...
dspzl.org.              3600    IN      A       192.30.252.153
dspzl.org.              3600    IN      A       192.30.252.154
```

But GitHub has changed their infrastructure and those records should now be:

185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

Once that's done we can flip the switch in the repo settings.

**Comment by DavidPurdy1** [comment]
And maybe I'm not too familiar with this but what is our DNS provider? I assume all I want to do for this is create an A record there with those github pages addresses and then change the repo settings. I don't have to like get a certificate or anything to set it up with our dns?

**Comment by yorker78** [comment]
I don't recall much about our DNS other than some alumni on the Facebook page I believe still maintains our account with whatever registrar. There was talk about switching the ownership to ACB, but I am unsure if that ever went through. Basically look through the Facebook page and see if you can find my post about it.

**Comment by DavidPurdy1** [comment]
Any updates from this? I saw there was an email, but I didn't see a response. I don't remember how to get into my facebook account and I don't think I am part of the right delta sig facebook page so I just have been too lazy to try and look for this.

**Comment by DavidPurdy1** [comment]
I can see that Jack is probably not the person we want for this and it is Andrew Augustine. Does anyone have their email address/would anyone know where I would be able to find it?

**Comment by yorker78** [comment]
You can probably post on the Facebook group/alumni forums and eventually get the attention of whoever owns it. It might take like a month because alumni are old and don't pay attention well.

**Comment by akn0d** [comment]
Yes, alumni are like toddlers with ADHD on eight balls. I own dspzl.org. The account has nothing else in it (domain wise) so I can transfer it easily. Happy to move it to google domains if that is what needs to happen. I have seen multiple "i can take it" messages from folks. Who actually wants to take the responsibility?

**Comment by DavidPurdy1** [comment]
I am currently the webmaster, I vote give it to @kleinpa. He is quite responsive and I think owns the group. If not him, maybe like @schwalbs ? As long as either ACB, the actives, or both know who to contact I think we are fine. I will put it in some transition doc for who owns it and info related to it.

**Comment by yorker78** [comment]
I've never had to buy domains for an org, just dumb jokes (R.I.P. colehansonisatwink.com) and a personal website. Is there someway to convert to an enterprise account with multiple admins to prevent single point of failure problems (like we have been)? Also inb4 ACB creates the probably unnecessary ACB position of Alumni tech dick or Alumni webmaster or something more appropriately named.

**Comment by kleinpa** [comment]
I'm happy to watch over it. Google Domains allows multiple owners so that would be my preference (trying not to shill too hard here). I can handle the transfer and set up the active webmaster with access.

**Comment by akn0d** [comment]
ok, I will send you the info to log in (to your gmail). 

Jack

**Comment by schwalbs** [comment]
@yorker78 we won't be doing that. But maybe we can attach the ACB secretary email account (dspzacbsecretary@gmail) account so ACB can manage it without bothering others.

**Comment by kleinpa** [comment]
@akn0d was able to share access to the DNS account with me and I updated the settings we needed to support IPv6 and SSL via GitHub Pages. Jack is still the owner of the account and only he can manage billing, users, and transfers, but I can help with updates in the future.
